#+HUGO_BASE_DIR: ~/Projects/blog/
#+HUGO_SECTION: posts
#+HUGO_AUTO_SET_LASTMOD: t
#+STARTUP: indent logdrawer

* Blog Posts

** DONE 落幕回响                                                      :随笔:
CLOSED: [2023-07-12 Wed 16:50]
:PROPERTIES:
:EXPORT_FILE_NAME: echo
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :featured_image ./images/peking.jpg
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description 当时光的列车将要朝着远离青春的方向从四年的最后一站驶出时，回首，我听见过去的声音在心底激起了回响
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2023-07-12 Wed 16:50]
:END:

*** 壹·燕园的十七个瞬间

大抵记忆是个低维空间吧，不然为何在记忆里搜寻到的关于这段经历的投影，只剩下了一个又一个瞬间呢？
好在这样的逼近不算太坏，依然留下那些最强烈、最深刻的情感，依然在回忆涌起时，再次与某个过去的瞬间产生共鸣。

我想起那些平凡美好的瞬间，想起树荫下猫咪的呵欠和肚子柔软的触感，想起出神时教室窗外那满墙的爬山虎，
还想起园子里不期而遇的一丛丛野花、一片片落叶，想起晚风吹拂下湖面荡开的、映着塔影的涟漪；

我怀念并肩共同历经的瞬间，怀念一起挥洒的汗水，怀念一起被早八、Deadline追赶的日子，
怀念把酒言欢、畅谈过往与未来的激昂，也怀念失意萧索时的倾听与陪伴；

我记得牵手一起走过的瞬间，记得望向你时默契交汇的视线，记得冬夜里手心的温度, 记得一起头顶璀璨星河、身披灿烂霞光，记得那些笑与泪；

我难忘独自探索迷茫的瞬间，难忘熙攘人流中匆匆的身影，难忘静夜里的一盏孤灯，更难忘梦里浮现的符号公式，难忘未名湖底的明月......

---

*** 贰·世界于此展开

要结束一段旅程的时候，总不自觉想要问自己，这段经历中我最主要的收获是什么？

我想大概不是那些课程里所学的内容，尽管修了快两百学分，当了快三年的考试周守门员，
也曾顶着新冠的高烧算视线内所有闭曲线的基本群，但多数知识都以及退化成脑海中某个模糊的名词，
只占据很小一部分的脑容量了；大概也不能说是遇到的人们，尽管收获了无数珍贵的情谊，
作为学生、同窗和助教帮助过许多人的同时也受到许多人的帮助，共度过许多美好的时光，
但人生的旅途总是有不断的相遇与别离，只好默默期待生命中的下一个路口，再度重相逢。

这一切在心底留下的东西究竟是什么呢？或许，是它们共同构成的，更广阔的世界。

**** 山的那边，还是山

我了解到了更广的知识，看见教科书上，一代又一代前辈毕生奉献的努力，不过浓缩成零星篇章里的只言片语，
也体会随着认识的深入，比起感受到自己知道了什么，更多的时候意识到的是自己的无知。

敬畏于人类知识体系的庞杂繁复的同时，也又一次想起东邪西毒里的那句「山的那边，还是山」。
也许山终究是攀登不完的，但当山顶在脚下时，更远的视线和远处更高的山峰，也更显露出更加广阔和真实的世界。

**** 自由与理想之歌

我还结识了更多的人，他们志趣各异，在不同的领域发光发热，
或学识渊博，引经据典使课堂妙趣横生；或热心服务，活跃于各类活动会场；
或多才多艺，将美的体验带给更多人；或擅于竞技，在比赛场上展露个人风采；
或坚定不移，朝既定目标持续努力；或捍卫自由，用行动为权益发声......

我在他们的身上看见了两样东西，一曰理想——正因此才对某种事物充满着热爱与激情，
去努力追求——人也应该学着[[https://en.wikipedia.org/wiki/Ring_(mathematics)][环]]的样子，至少有平凡的理想，否则与咸鱼何异也？
一曰自由，我看见不被设限的人生，看见生命的无限可能性，
看见有无数不同的美好值得去追求，看见差异被包容后不同追求的个体一同前行。

---

*** 叁·关于宇宙、人生以及任何事情的终极答案

#+begin_quote
How many roads must a man walk down

Before you call him a man?

......

The answer, my friend, is blowin' in the wind

The answer is blowin' in the wind

------ Bob Dylon, /Blowin' in the wind/
#+end_quote

忘记从什么时候开始，一直在寻找关于所谓终极命题的答案，我问过许多人，也得到过不少答案。

**** 灿若流星

一个我很喜欢的答案如是说：「流星划破天际只是短短一瞬，但就在那一瞬，它已将自己的灿烂留在夜空中」。

尽管这个答案并没有完全解答我的困惑，在无数彷徨的夜晚，我却总想到它，也想到李太白和苏东坡，
于是不安的心能看到更远大的时空、跳出当下的桎梏。

**** 解构理想主义

思考答案的过程也反过来作用在了我自己的身上，早先的时候我大概有些过于理想主义，
凡事都追求一种圆满和完美。想来思考这个问题的答案也大概出于希望人生也应该完备的想法。

然而这样的追求逐渐被打破了，Gödel、Kant、Turing 等人分别给我上了课，
让我明白有些事情不可能达到理想中的圆满，不只是做得还不够，而是这个世界的游戏规则不允许；
另外一群 +叫不出名字的+ 生物学家、心理学家和社会学家们也从旁佐证，某些角度上说，人类只是一群穿衣服的猴子。

虽然不知道猴子会不会思考猴生的意义这样的问题，我还是一度有些沮丧，像是失去了什么东西。
重新开始思考根本的追求时，偶然读到的《禅与摩托车维修艺术》给了我新的火种，这火种在之后不断燃烧，
在心中散发出这样的光：

也许人与人之间无法根本上互相理解，但相似的对共同美好的追求总将我们联系起来；

可能认识世界始终是个伪命题，但简洁、完备而优美的结果一定会在不同地方反复出现；

尽管在无限大的宇宙时空尺度下，人类是如此渺小，但总有小处值得去make a difference，总能在不同的地方闪耀属于人类的光辉。

**** 未知生，焉知死

后来听到了另一个印象深刻的答案，「如果你经历足够多，也许能自己找到答案」。
我想起孔子对子路说的话——未知生，焉知死——多么相似的奥卡姆剃刀式的答案，
彼时读《论语》没能理解它的意思，此刻心中的答案却逐渐清晰。

每个人都将会有自己的答案，又或者答案是什么并不重要，非要有的话，我想42很适合。


** DONE Indrew                                                     :Fiction:
CLOSED: [2024-04-29 Mon 18:12]
:PROPERTIES:
:EXPORT_FILE_NAME: rewind
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description 一切有为法，如梦幻泡影，如露亦如电，应作如是观。
:END:

*** I

浑身动弹不得，本能驱使下的不断挣扎，也只让呼吸愈发困难。

缓慢地吸一口气，收集来自身体各处的感受，似乎是被拘束带捆在钢架床上。

/这是……精神病院？/

极力辨认起眼前不见五指的漆黑，同时努力让呼救声透过嘴里塞着的毛巾。
似乎有几缕微弱的光传来，来不及激动，为了适应黑暗而放大的瞳孔就猛地紧缩，
跟着一阵阵从脊背直冲天灵的寒意。

——那微光，来自无数双淡漠凝视你的眼！

---

记不清是第几次，又进入同一个梦魇了。

翊在办公室醒来，望着窗外的乌云出神——不知怎地，睡前关好的窗竟大开着，
下意识伸手去够桌上的水杯时也扑了个空。头依然疼得厉害，大概因为那件事，
最近精神过于紧绷了，等一切尘埃落定后，给自己一些放松的时间好了。

*** II

时钟指向下午三点整，敲门声响起。

「进来吧。」

一个黑色身影推门而入，径直走到翊的面前，低头看向桌对面的翊，神情里透着严肃。

「关于那件事情，你考虑得如何了？」黑影开门见山道。

「我不同意。」

来者是翊的大学同学兼这间公司的合伙人隆，平日里常四处奔走于公司的市场化业务，
如果不是因为他口中的“那件事”，想来不会在出现在此时此地。

「为什么呢？」隆似乎对翊的回答并不意外，「我们最新的技术突破领先业内，
正是借上市的东风抢占市场先机的绝佳机会。」

「现有的小范围场景下的数字模拟都需要大量进一步的测试观察，
新技术距离实际可用还有相当远的距离，也不是我们目前的算力能支持的。」

「不管是上线还是测试，都需要更多的资金，你也不希望看到自己的心血被埋没不是吗？
只要给投资人们做个演示让公司顺利上市，你说的这些都不会是问题。」

「……」

*** III

两人正进行的争论，围绕着公司的核心业务——数字脑——脑机时代新兴的技术，
通过特殊材料将人脑状态扫描存储下来，就能利用特质的计算设备模拟人脑活动。
这样的模拟大脑也可以接入脑机服务器运营的虚拟世界中与接入其中的真人交互，
数字脑的应用前景非常广泛：

在亲友弥留之际保存他们的大脑状态，通过脑机接入后，
客户可以在脑机服务器运行的虚拟世界中与模拟的亲友重聚；
虚拟世界的服务提供商们，只需将经过特定培训的员工们的大脑状态记录，
就可以批量实现媲美真人扮演的 NPC 角色；
一些更加大胆的人们甚至畅想通过这样的形式延长自己的生命！
然而这类应用仍面临伦理学方面的巨大争议。

抛开伦理学方面的争议，技术层面上，也限制了目前这样的模拟只能非常小的时空范围内实现。
即便如此，这样的模拟也常因为各种不可控因素崩溃，这时只能从崩溃之前最后的状态恢复，
这样的限制使得这项技术离真正好用还有一段距离。

沉默良久，翊再次开口：

「我想要对公司和技术完全的控制权，不管你怎么说，我都不会考虑上市。」

争执未果，隆一反常态地没有大发雷霆，淡淡留下一句「我会想另寻他法。」便转身离开。

*** IV

异常平静的隆却让翊更加轻松不起来。

/按照他的性格，这件事一定不会这么简单就结束。/

翊有些心烦意乱，打算到门外透透气。

拧开门的一瞬间，突然天旋地转。

---

翊有些心烦意乱，打算用工作转移自己的注意力。

翊将保存着核心技术的安全介质接入脑机，凭借着自己的肌肉记忆输入起密钥。
莫名地，他呆住了——肌肉“失忆”了——好像这段密钥从来没有被自己输入过。
他只好转而求助自己的大脑，隐隐作痛的头让他感到从记忆中提取信息异常困难，

/也许这也和最近发生的一连串怪事有关系？/

有些怀疑地敲下最后几位：

「7-@-5-$-」

已经做好错误准备的他，稍有些意外地，听到了检验通过的清脆提示音。

可一件令他感到更加奇怪的事情发生了，翊惊出一身冷汗，接着一阵目眩。

---

翊办公桌前的人输入了最后几位密钥：「7-@-5-$-」，响起的却是急促而刺耳的错误提示。
他摇了摇头，心里叹道： /还是不行吗？/

将这个错误的尝试记录在某个地方，他操作起脑机里名为 =翊-15:33.status= 的文件，
选择了 *恢复模拟* 。

*** V

「7-@-5-$」，翊有些怀疑敲下最后几位后，预期之中的错误提示响起，

#+begin_quote
*警告：* 密钥错误，将在 10 次失败尝试后抹除所有内容！
#+end_quote

……

翊输入完密钥的最后一位，短促的错误提示又一次响起，只剩最后三次机会。

翊有些不安，试了这么多次竟然都不对实在反常，反复确认安全介质没有被调换后，
他揉了揉头，更加细致地检索起记忆的每个角落……

随着又一次输入完成，万幸的是，清脆的声音响起，用完所有试错机会之前，终于成功了。

/发生了什么？介质里的内容怎么全部消失了？/

翊一边脑海闪过无数推测，一边镇定地去找用于恢复的备份，却渐渐感到呼吸困难。

---

清脆的声音响起，黑色的身影长舒一口气，还好在限制的次数之内解开了，
简单确认其中的内容，放下了悬着的一颗心。

/我知道说服不了你的，但你也知道我不会轻易罢休，对不起只能用这样特殊的方法了。/
/等这份内容得到投资人认可，公司成功上市后，你会感谢我的。/

隆插入自己的安全介质，开始拷贝刚刚解开的核心技术内容。

按耐不住兴奋的他全然没有意识到，自己的介质里空空如也。

隆开始感到意识模糊……

* Blog Drafts

